#
# DO NOT EDIT THIS FILE!  Customize your shell in ~/.profile.d/*.sh, instead.
#

if [ "$BASH" -a -f "$HOME/.bashrc" ]
then . "$HOME/.bashrc"
fi

mesg n

for PATHNAME in "$HOME/.profile.d/"*".sh"
do . "$PATHNAME"
done
