#
# DO NOT EDIT THIS FILE!  Customize your shell in ~/.profile.d/*.sh, instead.
#

if [ "$BASH" -a -f "$HOME/.bashrc" ]
then . "$HOME/.bashrc"
fi

chgrp "tty" "$(tty)"
mesg y

for PATHNAME in "$HOME/.profile.d/"*".sh"
do . "$PATHNAME"
done

if ! which "sw_vers" >"/dev/null" 2>"/dev/null" && which "tmux" >"/dev/null" 2>"/dev/null" && [ -z "$TMUX" ]
then
    if tmux has-session
    then exec tmux attach
    else exec tmux new
    fi
fi
